server:
  port: 8085
  
spring:
  application:
      name: portfolio-service


# Eureka client
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

feign:
  client:
    config:
      stock-web-service:
        connectTimeout: 600000
        readTimeout: 600000
